- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes
- name: Install git
  dnf:
    name: git
    state: latest
- name: Install vim
  dnf:
    name: vim
    state: latest
- name: Install podman
  dnf:
    name: podman
    state: latest
- name: Install podman-compose
  dnf:
    name: podman-compose
    state: latest
- name: Install buildah
  dnf:
    name: buildah
    state: latest
- name: Create vscdev user
  ansible.builtin.user:
    name: vscdev
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: vscdev
    state: present
    key: "{{ lookup('file', vagrant_ssh_pub_key) }}"
- name: Add podman to docker alias to bashrc
  ansible.builtin.lineinfile:
    path: /home/vscdev/.bashrc
    line: alias docker=podman
    owner: vscdev
    search_string: alias docker=podman
    state: present
    insertafter: EOF
    create: yes
- name: Add podman-compose to docker-compose alias to bashrc
  ansible.builtin.lineinfile:
    path: /home/vscdev/.bashrc
    line: alias docker-compose=podman-compose
    owner: vscdev
    search_string: alias docker-compose=podman-compose
    state: present
    insertafter: EOF
    create: yes
- name: Set hard memlock limit for vscdev
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: vscdev hard memlock -1
    owner: root
    search_string: vscdev hard memlock -1
    state: present
    insertafter: EOF
    create: yes
- name: Set soft memlock limit for vscdev
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: vscdev soft memlock -1
    owner: root
    search_string: vscdev soft memlock -1
    state: present
    insertafter: EOF
    create: yes