- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes
- name: Install git
  dnf:
    name: git
    state: latest
- name: Install vim
  dnf:
    name: vim
    state: latest
- name: Install podman
  dnf:
    name: podman
    state: latest
- name: Install podman-compose
  dnf:
    name: podman-compose
    state: latest
- name: Install buildah
  dnf:
    name: buildah
    state: latest
- name: Create vscdev user
  ansible.builtin.user:
    name: vscdev
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: vscdev
    state: present
    key: "{{ lookup('file', vagrant_ssh_pub_key) }}"
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/vscdev/.local/bin
    state: directory
    owner: vscdev
    group: vscdev
    mode: '0700'
- name: Create a symbolic link named docker for podman
  ansible.builtin.file:
    src: /usr/bin/podman
    dest: /home/vscdev/.local/bin/docker
    owner: vscdev
    group: vscdev
    state: link
- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/bin/podman-compose
    dest: /home/vscdev/.local/bin/docker-compose
    owner: vscdev
    group: vscdev
    state: link
- name: Set hard memlock limit for vscdev
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: vscdev hard memlock -1
    owner: root
    search_string: vscdev hard memlock -1
    state: present
    insertafter: EOF
    create: yes
- name: Set soft memlock limit for vscdev
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: vscdev soft memlock -1
    owner: root
    search_string: vscdev soft memlock -1
    state: present
    insertafter: EOF
    create: yes